version: '3.7'
services:

  run_data_biobase:
    build: .
    environment:
      - GC_NEO4J_URL=bolt://${LOCAL_NEO4J_HOST}:7687
      - GC_NEO4J_USER=neo4j
      - GC_NEO4J_PASSWORD=${LOCAL_NEO4J_PASSWORD}
      - RUN_MODE=${RUN_MODE}
    volumes:
      - type: bind
        source: ${DOWNLOAD_PATH}
        target: /download