version: '3.7'
services:

  run_data_biobase:
    build: .
    environment:
      - RUN_MODE=${RUN_MODE}
      - NEO4J=${NEO4J}
    volumes:
      - type: bind
        source: ${DOWNLOAD_PATH}
        target: /download